### ISSUE TITLE
Hackrf Hardware?

### ISSUE THREAD

**Issue by curtisklarsen** [r4d10n/retrogram-rtlsdr#3]
Can this work with the Hackrf Hardware?

**Comment by r4d10n** [comment]
Check https://github.com/r4d10n/retrogram-soapysdr

**Comment by curtisklarsen** [comment]
How does one connect retrogram-soapysdr to a hackrf? 

I see this on the website:

./retrogram-soapysdr --dev 0 --rate 1.8e6 --freq 100e6 --step 1e5

I assume "dev"  is the USB port that the hackrf is connected on?  What
if I want to show the frequency range from 5.0 to 5.8GHz?  What would
the syntax look like?

>

**Comment by r4d10n** [comment]
Dear Curtis,

dev parameter is used for selection from multiple soapysdr devices
connected. If I remember correctly, you can try SoapySDRUtil --probe to get
the listing. Mostly 0 should do, if you are using a single device.

Set freq parameter to 5.0e9 and rate parameter to the max rate hackrf can
support (20e6?). You can vary all those parameters on runtime using the
keys mentioned in the git page.

Cheers
