### ISSUE TITLE
License

### ISSUE THREAD

**Issue by henrikssn** [r4d10n/retrogram-rtlsdr#4]
I have a PR I would like to submit, but I would require you to license your code under an OSS license due to my current employer.

Would you please mind licensing your code under some reasonable open source license (e.g. any of Apache 2, MIT, BSD, GPL-3, etc)?

**Comment by henrikssn** [comment]
Oh, I found this in the source code:

```
// SPDX-License-Identifier: GPL-3.0-or-later
```

Maybe worth checking in a LICENSE file for GPL-3?

**Comment by r4d10n** [comment]
Done. Let me know what the PR is about. 

Cheers

Rakesh

**Comment by henrikssn** [comment]
Thanks! Lets continue the discussion in #5
